name: build_cont
on: [pull_request]
jobs:
  build:
    name: Build on ${{ matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: [ 'ubuntu:16.04', 'ubuntu:18.04', 'ubuntu:20.04' ]
        # python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Install system-wide dependencies
      run: |
        apt-get update
        apt-get install -y lilypond qpdf python3 python3-pip git
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        make
        make all_tunes
